name: alphabet_list_view_example
description: Demonstrates how to use alphabet_list_view.
publish_to: 'none'
version: 1.0.3+4

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  alphabet_list_view:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  cosee_lints: ^0.10.1
  dart_code_linter: ^2.0.0

flutter:
  uses-material-design: true
