name: alphabet_list_view
description: A ListView with sticky headers and an iOS-like clickable sidebar.
version: 0.1.1
repository: https://github.com/cosee/alphabet_list_view

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_sticky_header: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  dart_code_metrics: ^4.8.1

flutter:
