name: alphabet_list_view
description: A ListView with sticky headers and an iOS-like clickable sidebar.
version: 1.1.3
repository: https://github.com/cosee/alphabet_list_view/tree/main
issue_tracker: https://github.com/cosee/alphabet_list_view/issues
homepage: https://pub.dev/publishers/cosee.biz/packages
screenshots:
  - description: 'Default appearance of AlphabetListView'
    path: example/screenshots/default.webp
topics:
  - list

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_sticky_header: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  cosee_lints: ^0.7.0
  dart_code_linter: ^2.0.0
