name: alphabet_list_view

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2.11.0

      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            .dart_tool/
          key: ${{ runner.os }}-dependencies-${{ hashFiles('**/pubspec.lock') }}
      - name: Install dependencies
        run: flutter pub get

      - name: Format code
        run: dart format --set-exit-if-changed .
      - name: Analyze code
        run: flutter analyze
      - name: Run Code metrics
        run: dart run dart_code_metrics:metrics analyze . --set-exit-on-violation-level=warning --disable-sunset-warning
      - name: Run tests
        run: flutter test

  pana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2.11.0

      - name: Install WebP
        run: |
          sudo apt update
          sudo apt install webp
      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            .dart_tool/
          key: ${{ runner.os }}-dependencies-${{ hashFiles('**/pubspec.lock') }}
      - name: Install Dependencies
        run: |
          flutter pub get
          flutter pub global activate pana

      - name: Verify Pub Score
        run: ./tool/verify_pub_score.sh
